In [1]:
import numpy as np

In [3]:
A=np.random.randint(20,50,(2,3))

In [4]:
B=np.random.randint(20,50,(2,3))

In [5]:
A

array([[42, 37, 23],
       [39, 42, 32]])

In [6]:
B

array([[22, 21, 34],
       [45, 44, 39]])

In [7]:
A+B

array([[64, 58, 57],
       [84, 86, 71]])

In [8]:
A-B

array([[ 20,  16, -11],
       [ -6,  -2,  -7]])

In [9]:
A/B

array([[1.90909091, 1.76190476, 0.67647059],
       [0.86666667, 0.95454545, 0.82051282]])

In [10]:
A

array([[42, 37, 23],
       [39, 42, 32]])

In [11]:
A+7

array([[49, 44, 30],
       [46, 49, 39]])

In [12]:
C=np.array([2,1,5])

In [13]:
D=np.array([2,4,5,6])

In [14]:
C+D

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [15]:
A+D

ValueError: operands could not be broadcast together with shapes (2,3) (4,) 

In [16]:
A+C

array([[44, 38, 28],
       [41, 43, 37]])

In [17]:
A

array([[42, 37, 23],
       [39, 42, 32]])

In [18]:
C

array([2, 1, 5])

In [21]:
D

array([2, 4, 5, 6])

In [22]:
B

array([[22, 21, 34],
       [45, 44, 39]])

In [23]:
D

array([2, 4, 5, 6])

In [24]:
E=np.array([4]) #:[4,4,4,4]

In [25]:
D+E

array([ 6,  8,  9, 10])

In [28]:
F=np.array([2,4])

In [27]:
D+F

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [29]:
A

array([[42, 37, 23],
       [39, 42, 32]])

In [30]:
H=np.array([[3],[6]])

In [31]:
A

array([[42, 37, 23],
       [39, 42, 32]])

In [32]:
H

array([[3],
       [6]])

In [33]:
A+H

array([[45, 40, 26],
       [45, 48, 38]])

## Realtional and logical operations

In [34]:
D

array([2, 4, 5, 6])

In [35]:
D>3

array([False,  True,  True,  True])

In [36]:
A

array([[42, 37, 23],
       [39, 42, 32]])

In [37]:
A<42

array([[False,  True,  True],
       [ True, False,  True]])

In [38]:
A>30 and A<42

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [39]:
A>30 & A<42

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [40]:
(A>30) & (A<42)

array([[False,  True, False],
       [ True, False,  True]])

In [41]:
A>30

array([[ True,  True, False],
       [ True,  True,  True]])

In [42]:
A<42

array([[False,  True,  True],
       [ True, False,  True]])

In [43]:
(A>30) or (A<42)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [44]:
(A>30) | (A<42)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [45]:
A>30

array([[ True,  True, False],
       [ True,  True,  True]])

In [47]:
~(A>30)

array([[False, False,  True],
       [False, False, False]])

## Indexing and Slicing 

In [48]:
x=[3,4,6,8,5,7]

In [49]:
x[1]

4

In [50]:
y=[[3,5],[5,6],[5,3,6]]


In [51]:
y[0]

[3, 5]

In [52]:
y[-1]

[5, 3, 6]

In [53]:
y[2]

[5, 3, 6]

In [54]:
y[1]

[5, 6]

In [55]:
y[1][1]

6

In [56]:
y[2][1]

3

In [57]:
y[2,1]

TypeError: list indices must be integers or slices, not tuple

In [59]:
z=np.array([[3,5],[5,6],[3,6]])

In [60]:
z

array([[3, 5],
       [5, 6],
       [3, 6]])

In [61]:
z[1][1]

6

In [62]:
z[1,1]

6

In [63]:
z[-1,0]

3

In [64]:
z[-1][0]

3

In [65]:
x

[3, 4, 6, 8, 5, 7]

In [67]:
x[0:3] # x[0:3:1]

[3, 4, 6]

In [68]:
x[0:5:2]#= x[:5:2]

[3, 6, 5]

In [70]:
x[::-1]

[7, 5, 8, 6, 4, 3]

In [71]:
x[::-2]

[7, 8, 4]

In [75]:
x[::2]

[3, 6, 5]

In [76]:
z

array([[3, 5],
       [5, 6],
       [3, 6]])

In [77]:
z_1=z.ravel()

In [78]:
z_1

array([3, 5, 5, 6, 3, 6])

In [80]:
z_1[:6:3]

array([3, 6])

In [82]:
z

array([[3, 5],
       [5, 6],
       [3, 6]])

In [83]:
z[:,0]

array([3, 5, 3])

In [84]:
z[:,-1]

array([5, 6, 6])

In [85]:
z[1:3,:]

array([[5, 6],
       [3, 6]])

In [86]:
z[::2]

array([[3, 5],
       [3, 6]])