In [2]:
a=[1,3,5,7]
b=[7,9,2,-5]
# result=[8,12,7,2]
result =[]
for i in zip(a,b):
    result.append(i[0]+i[1])
print(result)

[8, 12, 7, 2]


In [3]:
a=[1,3,5,7]
b=[7,9,2,-5]
# result=[8,12,7,2]
result =[]
for x,y in zip(a,b):
    result.append(x+y)
print(result)

[8, 12, 7, 2]


In [4]:
a=[1,3,5,7]
b=[7,9,2,-5]
result =[x+y for x,y in zip(a,b)]
print(result)

[8, 12, 7, 2]


In [5]:
a+b

[1, 3, 5, 7, 7, 9, 2, -5]

In [6]:
a=[1,3,5,7]
b=[7,9,2,-5]
# result=[8,12,7,2]
result =[]
for i in range(len(a)):
    result.append(a[i]+b[i])
print(result)

[8, 12, 7, 2]


In [7]:
import numpy as np

In [8]:
type(a)

list

In [9]:
a= np.array(a)
b=np.array(b)
c=np.array([4,6,3,6,8])
d=np.array((3,5,5,3))


In [10]:
a

array([1, 3, 5, 7])

In [11]:
type(a)

numpy.ndarray

In [12]:
a

array([1, 3, 5, 7])

In [13]:
b

array([ 7,  9,  2, -5])

In [14]:
a+b

array([ 8, 12,  7,  2])

In [15]:
a*b

array([  7,  27,  10, -35])

In [16]:
a/b

array([ 0.14285714,  0.33333333,  2.5       , -1.4       ])

In [17]:
b**a

array([     7,    729,     32, -78125])

In [18]:
x=[1,2.5,5,7.2]

In [19]:
x

[1, 2.5, 5, 7.2]

In [20]:
x=np.array(x)

In [21]:
x

array([1. , 2.5, 5. , 7.2])

In [23]:
y=np.array([1,2.5,5,7.2,"10"])

In [24]:
y

array(['1', '2.5', '5', '7.2', '10'], dtype='<U32')

# Attributes

In [25]:
a

array([1, 3, 5, 7])

In [26]:
a.dtype

dtype('int64')

In [27]:
x.dtype

dtype('float64')

In [28]:
y.dtype

dtype('<U32')

In [29]:
a.shape

(4,)

In [30]:
D=np.array([[3,4,6],[5,6,8]])

In [31]:
D

array([[3, 4, 6],
       [5, 6, 8]])

In [32]:
D.shape

(2, 3)

In [33]:
a.size

4

In [34]:
D.size

6

In [35]:
a.ndim

1

In [36]:
D.ndim

2

In [37]:
a

array([1, 3, 5, 7])

In [38]:
D

array([[3, 4, 6],
       [5, 6, 8]])

In [39]:
E=np.array([[3,5,6],[4,1,4],[5,6,7],[5,7,4]])

In [40]:
E

array([[3, 5, 6],
       [4, 1, 4],
       [5, 6, 7],
       [5, 7, 4]])

In [41]:
E.shape

(4, 3)

In [42]:
E.size

12

In [43]:
E.ndim

2

In [49]:
w=np.array([[[4,6,4],[5,6,5]],[[5,6,6],[6,-2,6]]])

In [50]:
w

array([[[ 4,  6,  4],
        [ 5,  6,  5]],

       [[ 5,  6,  6],
        [ 6, -2,  6]]])

In [51]:
w.shape

(2, 2, 3)

In [48]:
w.ndim

3

In [53]:
s=np.array([[[1],[-4],[0]],[[5],[6],[10]]])

In [54]:
s.shape

(2, 3, 1)

In [55]:
s.ndim

3

In [56]:
a.shape

(4,)

In [57]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [59]:
np.zeros(2,dtype="int16")

array([0, 0], dtype=int16)

In [60]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [61]:
np.ones(2)

array([1., 1.])

In [66]:
np.ones(4)

array([1., 1., 1., 1.])

In [64]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [70]:
np.random.randint(1,6)

4

In [71]:
np.random.randint(1,6,5)

array([5, 2, 2, 5, 1])

In [72]:
np.random.randint(0,100,10)

array([44,  2, 27,  8, 39, 20,  2, 86, 32, 38])

In [73]:
 np.random.randint(1,6,(4,6))

array([[1, 2, 5, 4, 4, 2],
       [5, 5, 3, 1, 2, 4],
       [4, 1, 3, 2, 2, 1],
       [3, 2, 1, 4, 1, 3]])